const ShopActionTypes = {
    FETCHING_COLLECTIONS_STARTED: 'FETCHING_COLLECTIONS_STARTED',
    FETHCING_COLLECTIONS_SUCCEED: 'FETHCING_COLLECTIONS_SUCCEED',
    FETHCING_COLLECTIONS_FAILED: 'FETHCING_COLLECTIONS_FAILED'
}

export default ShopActionTypes;