const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    GOOGLE_SIGN_IN_STARTED: 'GOOGLE_SIGN_IN_STARTED',
    EMAIL_SIGN_IN_STARTED: 'EMAIL_SIGN_IN_STARTED',
    SIGN_IN_SUCCEED: 'SIGN_IN_SUCCEED',
    SIGN_IN_FAILED: 'SIGN_IN_FAILED',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_OUT_STARTED: 'SIGN_OUT_STARTED',
    SIGN_OUT_SUCCEED: 'SIGN_OUT_SUCCEED',
    SIGN_OUT_FAILED: 'SIGN_OUT_FAILED',
    SIGN_UP_STARTED: 'SIGN_UP_STARTED',
    SIGN_UP_SUCCEED: 'SIGN_UP_SUCCEED',
    SIGN_UP_FAILED: 'SIGN_UP_FAILED'
}

export default UserActionTypes;